# Generated by Django 5.2.1 on 2025-05-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="descreption",
            new_name="description",
        ),
    ]
